[package]
name = "pdfv-core"
description = "Core validation contracts and library API for pdfv."
categories = ["development-tools"]
keywords = []
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
aes = { workspace = true, optional = true }
cbc = { workspace = true, optional = true }
cipher = { workspace = true, optional = true }
md-5 = { workspace = true, optional = true }
rc4 = { workspace = true, optional = true }
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = { workspace = true, optional = true }
subtle = { workspace = true, optional = true }
tempfile.workspace = true
thiserror.workspace = true
typed-builder.workspace = true
flate2 = { workspace = true, optional = true }
quick-xml.workspace = true
regex.workspace = true

[dev-dependencies]
config.workspace = true
criterion.workspace = true
flate2.workspace = true
proptest.workspace = true
rstest.workspace = true
serde_json.workspace = true

[[bench]]
name = "parser_m1"
harness = false

[[bench]]
name = "model_traversal_m6"
harness = false

[[bench]]
name = "content_stream_m6"
harness = false

[features]
default = ["json", "flate", "decrypt"]
json = []
flate = ["dep:flate2"]
custom-profiles = []
bench = []
decrypt = ["dep:aes", "dep:cbc", "dep:cipher", "dep:md-5", "dep:rc4", "dep:sha2", "dep:subtle"]
