[package]
name = "pdfv-core"
description = "Core validation contracts and library API for pdfv."
categories = ["development-tools"]
keywords = []
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
typed-builder.workspace = true

[dev-dependencies]
serde_json.workspace = true

[features]
default = ["json", "flate"]
json = []
flate = []
custom-profiles = []
bench = []
