[package]
name = "pdfv"
description = "Command-line interface for the pdfv validator."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
clap.workspace = true
pdfv-core.workspace = true
