[package]
name = "pdfv"
description = "Command-line interface for the pdfv validator."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
config.workspace = true
pdfv-core = { workspace = true, features = ["custom-profiles"] }
rayon.workspace = true
serde.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
md-5.workspace = true
predicates.workspace = true
rc4.workspace = true
tempfile.workspace = true
